# Generated by Django 4.1.1 on 2022-09-27 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lasttname", models.CharField(max_length=100)),
                ("wikipedia", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                ("summary", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("AV", "Aventure"),
                            ("TR", "Thriller"),
                            ("FS", "Fantastique"),
                            ("RM", "Romance"),
                            ("HR", "Horreur"),
                            ("SF", "Science_fiction"),
                        ],
                        max_length=20,
                    ),
                ),
                ("stock", models.IntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="GestionLivre.author",
                    ),
                ),
            ],
        ),
    ]
