# Generated by Django 4.1.1 on 2022-10-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GestionLivre", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="firstname",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="author",
            name="lasttname",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="author", name="wikipedia", field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AV", "Aventure"),
                    ("TR", "Thriller"),
                    ("FS", "Fantastique"),
                    ("RM", "Romance"),
                    ("HR", "Horreur"),
                    ("SF", "Science_fiction"),
                ],
                max_length=25,
            ),
        ),
    ]
