# Generated by Django 4.1.1 on 2022-10-04 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GestionLivre", "0002_alter_author_firstname_alter_author_lasttname_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author", old_name="lasttname", new_name="lastname",
        ),
    ]
